services:
  workspace:
    build:
      context: ../..
      dockerfile: ./run/devcontainer/Dockerfile
      args:
        - CONTAINER_UID=${CONTAINER_UID:?}
        - CONTAINER_GID=${CONTAINER_GID:?}
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
        - http_proxy
        - https_proxy
        - no_proxy
    command: sleep infinity
    volumes:
      - ../..:/workspace
